#!/bin/sh
# -*-makefile-gmake-*- \
# the next line restarts using GNU Make \
exec make -f "$0" ${1+"$@"}

# user-overridable vars
NDK := /opt/s/android-ndk-r10e
VER := 4.4-beta
SRC := bash-$(VER).tar.gz
ARCH := arm
TARGET := $(ARCH)-linux-androideabi
PLATFORM := android-9
# expected directory after unpacking the tarball
src.dir := $(basename $(basename $(SRC)))



.DELETE_ON_ERROR:
pp-%:
	@echo "$(strip $($*))" | tr ' ' \\n

mk := $(realpath $(lastword $(MAKEFILE_LIST)))
mk.dir := $(dir $(mk))

define help :=
Cross-compiles bash $(VER) w/ Android NDK.

Quick build:

	$$ $(notdir $(mk)) NDK=$(NDK) compile

NDK is a path to the installed Android NDK.
Override some defaults (everything is case-sensitive):

	$$ $(notdir $(mk)) NDK=$(NDK) SRC=$(SRC) TARGET=$(TARGET) PLATFORM=$(PLATFORM) ARCH=$(ARCH) compile

Targets:
	unpack
	toolchain
	config
	patch
	compile
	clean
endef

.PHONY: help
help:
	$(info $(help))@:



bash.patch := $(mk.dir)/bash-on-android.data
buildroot := build-$(ARCH)-bash-$(VER)
toolchain.dir := android-toolchain-$(TARGET)

path.orig := $(PATH)
PATH = $(realpath $(toolchain.dir))/bin:$(path.orig)
export CC := $(TARGET)-gcc
export LD := $(TARGET)-ld
export AS := $(TARGET)-as

unpack.target := $(src.dir)/.gmake.unpack
.PHONY: unpack
unpack: $(unpack.target)
$(unpack.target): $(SRC)
	tar xfz $<
	touch $@

toolchain.target := $(toolchain.dir)/.gmake.toolchain
.PHONY: toolchain
toolchain: $(toolchain.target)
$(toolchain.target):
	$(NDK)/build/tools/make-standalone-toolchain.sh \
		--platform=$(PLATFORM) --install-dir=$(toolchain.dir) \
		--arch=$(ARCH)
	touch $@

$(buildroot):
	mkdir -p $(@)

# FIXME: patch aclocal.m4 instead
export bash_cv_job_control_missing := present
config.target := $(buildroot)/.gmake.config
.PHONY: config
config: $(config.target)
$(config.target): $(toolchain.target) $(unpack.target) | $(buildroot)
	cd $(buildroot) && $(realpath $(src.dir))/configure --host=$(TARGET) \
		--disable-nls \
		--enable-static-link \
		--with-bash-malloc=no
	touch $@

patch.target := $(src.dir)/.gmake.patch
patch.file.01 := $(src.dir)/.gmake.patch.file.01
.PHONY: patch
patch: $(patch.target)
$(patch.target): | $(config.target)
	$(file > $(patch.file.01),$(patch.01))
	cd $(src.dir) && patch -p1 < $(notdir $(patch.file.01))
	touch $@

patch-view:
	$(file > /dev/stdout,$(patch.01))

compile.target := $(buildroot)/.gmake.compile
.PHONY: compile
compile: $(compile.target)
$(compile.target): $(patch.target)
	cd $(buildroot) && make
	touch $@

.PHONY: clean
clean:
	rm -rf $(buildroot) $(src.dir) $(toolchain.dir)



define patch.01 :=
diff -ru bash-4.4-beta.orig/bashline.c bash-4.4-beta/bashline.c
--- bash-4.4-beta.orig/bashline.c	2015-08-09 00:25:28.000000000 +0300
+++ bash-4.4-beta/bashline.c	2015-12-19 12:14:11.715797038 +0200
@@ -20,6 +20,12 @@

 #include "config.h"

+/* those 3 are meaningless on Android, see libc/include/grp.h in
+   bionic */
+struct group *getgrent(void) { return NULL; }
+void setgrent() {}
+void endgrent() {}
+
 #if defined (READLINE)

 #include "bashtypes.h"
Only in bash-4.4-beta: .gmake.patch
diff -ru bash-4.4-beta.orig/lib/sh/oslib.c bash-4.4-beta/lib/sh/oslib.c
--- bash-4.4-beta.orig/lib/sh/oslib.c	2013-10-14 16:12:57.000000000 +0300
+++ bash-4.4-beta/lib/sh/oslib.c	2015-12-19 12:14:11.717797006 +0200
@@ -33,7 +33,7 @@
 #  include <limits.h>
 #endif

-#include <posixstat.h>
+/* #include <posixstat.h> */
 #include <filecntl.h>
 #include <bashansi.h>

diff -ru bash-4.4-beta.orig/parse.y bash-4.4-beta/parse.y
--- bash-4.4-beta.orig/parse.y	2015-10-02 15:21:12.000000000 +0300
+++ bash-4.4-beta/parse.y	2015-12-19 13:27:43.126811344 +0200
@@ -129,7 +129,7 @@
 extern int bash_input_fd_changed;
 #endif

-extern int errno;
+/* extern int errno; */
 /* **************************************************************** */
 /*								    */
 /*		    "Forward" declarations			    */

endef
